requiered-players: 1
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 100
  y: 100
  z: 100
  pitch: 100
  yaw: 100
arenas:
  0:
    world: 'world'
    x: 10
    y: 100
    z: 100
    pitch: 100
    yaw: 100
  1:
    world: 'world'
    x: 10
    y: 100
    z: 100
    pitch: 100
    yaw: 100